<h1><u><i><center>Exercise 2: Matrix Operation</center></i></u></h1>

<i><u>Aim:</u>
<p>Write a program to input 2 matrices from the user and find the following:</p>
    <ol>
        <li>Dot Product</li>
        <li>Transpose</li>
        <li>Determinant</li>
        <li>Inverse</li>
        <li>Trace</li>
        <li>Rank</li>
        <li>Eigenvalues and Eigenvectors</li>
    </ol>

In [12]:
import numpy as np

<h3>Creating a matrix</h3>

In [25]:
r1,c1=list(map(int,input("Enter no of rows and cols for matrix 1:").split()))
r2,c2=list(map(int,input("Enter no of rows and cols for matrix 2:").split()))
m=list(map(int,input("Enter elements of matrix 1:").split()))
m1=np.array(m).reshape(r1,c1)
m=list(map(int,input("Enter elements of matrix 2:").split()))
m2=np.array(m).reshape(r2,c2)
print("Matrix 1:")
print(m1)
print("\nMatrix 2:")
print(m2)

Enter no of rows and cols for matrix 1: 2 2 
Enter no of rows and cols for matrix 2: 2 2 
Enter elements of matrix 1: 1 2 3 4 
Enter elements of matrix 2:  7 6 5 4


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[7 6]
 [5 4]]


<h5>1. Dot Product (Matrix Multiplication)</h5>

In [34]:
dot = np.dot(m1,m2)
dot

array([[17, 14],
       [41, 34]])

<h5>2. Transpose</h5>

In [63]:
t1 = np.transpose(m1)
t2 = np.transpose(m2)
t1,t2

(array([[1, 3],
        [2, 4]]),
 array([[7, 5],
        [6, 4]]))

<h5>3. Determinant</h5>

In [73]:
d = np.linalg.det(m1)
d

-2.0000000000000004

<h5>4. Inverse</h5>

In [75]:
i = np.linalg.inv(m1)
i

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<h5>5. Trace</h5>

In [80]:
t = np.trace(m1)
t

5

<h5>6. Rank</h5>

In [86]:
r = np.linalg.matrix_rank(m1)
r

2

<h5>7. Eigenvalues and Eigenvectors</h5>

In [104]:
eval,eve = np.linalg.eig(m1)
print(eval,'\n\n',eve)

[-0.37228132  5.37228132] 

 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
